#!/usr/bin/env bash
set -euo pipefail

# Directory containing files generated by
# E:\quadriga_data\generate_quadriga_interference_suite.m after manual copy to WSL.
CHANNEL_DIR="${CHANNEL_DIR:-data/quadriga_umi_nlos_interference_suite}"
CHECKPOINT_BASE="${CHECKPOINT_BASE:-checkpoints/generalization}"
TRAIN_PROFILES="${TRAIN_PROFILES:-tdl_mix_normalized umi_uma_mix_normalized}"
TRAIN_SEEDS="${TRAIN_SEEDS:-0 1 2}"
INTERFERENCE_MODES="${INTERFERENCE_MODES:-cochannel_full data_only}"
SNR_LIST="${SNR_LIST:-10}"
SIR_LIST="${SIR_LIST:-inf,20,10,5,0}"
PARTIAL_BAND_FRACTION="${PARTIAL_BAND_FRACTION:-0.25}"
SIR_NORMALIZATION="${SIR_NORMALIZATION:-per_frame}"
N0_MODE="${N0_MODE:-thermal}"
PHASE_MODE="${PHASE_MODE:-fixed}"
BATCH_SIZE="${BATCH_SIZE:-128}"
WINDOW_FRAMES="${WINDOW_FRAMES:-64}"
MAX_FRAMES="${MAX_FRAMES:-0}"
EVAL_SEED="${EVAL_SEED:-777000}"
DEVICE="${DEVICE:-cuda}"
RUN_ROOT="${RUN_ROOT:-runs/quadriga_interference}"
SKIP_EVALUATED="${SKIP_EVALUATED:-1}"

mkdir -p "$RUN_ROOT"
shopt -s nullglob
channel_files=("$CHANNEL_DIR"/quadriga_umi_nlos_interference_10m_seed*.mat)
if ((${#channel_files[@]} == 0)); then
    echo "No two-link MAT files found in: $CHANNEL_DIR" >&2
    exit 1
fi

for train_profile in $TRAIN_PROFILES; do
    for train_seed in $TRAIN_SEEDS; do
        invariant_checkpoint="$CHECKPOINT_BASE/$train_profile/single_branch_n0_gate_seed${train_seed}.pt"
        strict_checkpoint="$CHECKPOINT_BASE/$train_profile/strict_matched_complex_p_n0_gate_seed${train_seed}.pt"
        if [[ ! -f "$invariant_checkpoint" || ! -f "$strict_checkpoint" ]]; then
            echo "Missing A/C checkpoints for $train_profile seed $train_seed" >&2
            exit 1
        fi

        for channel_mat in "${channel_files[@]}"; do
            trajectory_name="$(basename "${channel_mat%.mat}")"
            for mode in $INTERFERENCE_MODES; do
                output_dir="$RUN_ROOT/$train_profile/seed_${train_seed}/$trajectory_name/${mode}_${SIR_NORMALIZATION}_${N0_MODE}"
                summary="$output_dir/quadriga_interference_summary.csv"
                if [[ "$SKIP_EVALUATED" == "1" && -f "$summary" ]]; then
                    echo "Skip existing: $summary"
                    continue
                fi
                echo "Run $train_profile seed=$train_seed trajectory=$trajectory_name mode=$mode"
                python -m evaluation.eval_quadriga_interference \
                    --channel_mat "$channel_mat" \
                    --invariant_checkpoint "$invariant_checkpoint" \
                    --strict_checkpoint "$strict_checkpoint" \
                    --output_dir "$output_dir" \
                    --snr_list="$SNR_LIST" \
                    --sir_list="$SIR_LIST" \
                    --interference_mode "$mode" \
                    --partial_band_fraction "$PARTIAL_BAND_FRACTION" \
                    --sir_normalization "$SIR_NORMALIZATION" \
                    --n0_mode "$N0_MODE" \
                    --phase_mode "$PHASE_MODE" \
                    --batch_size "$BATCH_SIZE" \
                    --window_frames "$WINDOW_FRAMES" \
                    --max_frames "$MAX_FRAMES" \
                    --seed "$EVAL_SEED" \
                    --device "$DEVICE"
            done
        done
    done
done

python -m evaluation.aggregate_quadriga_interference \
    --input_root "$RUN_ROOT" \
    --out_csv "$RUN_ROOT/quadriga_interference_aggregate.csv" \
    --paired_out_csv "$RUN_ROOT/quadriga_interference_paired_ac.csv"

echo "Completed: $RUN_ROOT"
